[tool.poetry]
name = "MOGESTpy"
version = "0.0.1"
description = "Water Resources Management Model"
authors = ["Dario Hachisu Hossoda <dario.hossoda@usp.br>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
documentation = ""
keywords = ["hydrology", "water resouces", "hydrological model"]

[tool.poetry.urls]
"Bug Tracker" = ""

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[project]
name = "mogestpy"